// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sjsu.minishare.model;

import com.sjsu.minishare.model.CloudUserDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CloudUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CloudUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CloudUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CloudUserIntegrationTest: @Transactional;
    
    @Autowired
    private CloudUserDataOnDemand CloudUserIntegrationTest.dod;
    
    @Test
    public void CloudUserIntegrationTest.testCountCloudUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = com.sjsu.minishare.model.CloudUser.countCloudUsers();
        org.junit.Assert.assertTrue("Counter for 'CloudUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindCloudUser() {
        com.sjsu.minishare.model.CloudUser obj = dod.getRandomCloudUser();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getUserId();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = com.sjsu.minishare.model.CloudUser.findCloudUser(id);
        org.junit.Assert.assertNotNull("Find method for 'CloudUser' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CloudUser' returned the incorrect identifier", id, obj.getUserId());
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindAllCloudUsers() {
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = com.sjsu.minishare.model.CloudUser.countCloudUsers();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CloudUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sjsu.minishare.model.CloudUser> result = com.sjsu.minishare.model.CloudUser.findAllCloudUsers();
        org.junit.Assert.assertNotNull("Find all method for 'CloudUser' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CloudUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CloudUserIntegrationTest.testFindCloudUserEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
        long count = com.sjsu.minishare.model.CloudUser.countCloudUsers();
        if (count > 20) count = 20;
        java.util.List<com.sjsu.minishare.model.CloudUser> result = com.sjsu.minishare.model.CloudUser.findCloudUserEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CloudUser' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CloudUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CloudUserIntegrationTest.testFlush() {
        com.sjsu.minishare.model.CloudUser obj = dod.getRandomCloudUser();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getUserId();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = com.sjsu.minishare.model.CloudUser.findCloudUser(id);
        org.junit.Assert.assertNotNull("Find method for 'CloudUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCloudUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CloudUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CloudUserIntegrationTest.testMerge() {
        com.sjsu.minishare.model.CloudUser obj = dod.getRandomCloudUser();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getUserId();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = com.sjsu.minishare.model.CloudUser.findCloudUser(id);
        boolean modified =  dod.modifyCloudUser(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.sjsu.minishare.model.CloudUser merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getUserId(), id);
        org.junit.Assert.assertTrue("Version for 'CloudUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
//    @Test
//    public void CloudUserIntegrationTest.testPersist() {
//        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", dod.getRandomCloudUser());
//        com.sjsu.minishare.model.CloudUser obj = dod.getNewTransientCloudUser(Integer.MAX_VALUE);
//        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide a new transient entity", obj);
//        org.junit.Assert.assertNull("Expected 'CloudUser' identifier to be null", obj.getUserId());
//        obj.persist();
//        obj.flush();
//        org.junit.Assert.assertNotNull("Expected 'CloudUser' identifier to no longer be null", obj.getUserId());
//    }
    
    @Test
    public void CloudUserIntegrationTest.testRemove() {
        com.sjsu.minishare.model.CloudUser obj = dod.getRandomCloudUser();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getUserId();
        org.junit.Assert.assertNotNull("Data on demand for 'CloudUser' failed to provide an identifier", id);
        obj = com.sjsu.minishare.model.CloudUser.findCloudUser(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CloudUser' with identifier '" + id + "'", com.sjsu.minishare.model.CloudUser.findCloudUser(id));
    }
    
}
